### ISSUE TITLE
CSS enhancements

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ps#1]
- [x] Add Z-index value to ensure its always on top.
- [x] Add some padding to the container, maybe 1em all the way around.
- [x] Remove Hover state, on second thought it doesn't look that great.
- [x] Remove focus state
- [x] The text color on hover changes to black. Can we have it be the same as the non-hover state? I tried to figure it out but couldn't.

**Comment by nickhamze** [comment]
@Mamaduka I tried editing the CSS myself and I committed it to Master. Hopefully I didn't mess anything up, just wanted to try something. If I did mess something up I'm sorry. 

I wasn't happy with the opacity hover state. I found a library of animated hover states so I tried one out that I thought looked pretty neat.

**Comment by Mamaduka** [comment]
@nickhamze I don't see any CSS changes committed to the repo. Maybe it's better to have some simple hover effect?

Fixes current text color issue on hover.

**Comment by nickhamze** [comment]
@Mamaduka obviously I suck at using git :) . What I did was implement the "buzz out" 2d effect from here (https://ianlunn.github.io/Hover/). Now that I've slept on it maybe it is a little much. Maybe the grow effect might be better. I'm not sure. What do you think? Motion always seemed like a good idea to me and not very many themes use it.

**Comment by Mamaduka** [comment]
Personally I would leave that to the theme preferences. If theme doesn't use motion hover effects this might seem out of the place.

Also adding good motion animation requires third-party libraries, which will be overkill for simple block plugin IMO.

**Comment by nickhamze** [comment]
ok. But I think we need to add this class "wp-block-post-script__button" to the button if we want it to inherit the theme styles. 

With that class added
<img width="197" alt="Screen Shot 2020-01-15 at 7 37 13 AM" src="https://user-images.githubusercontent.com/158918/72438209-f7ff0300-3769-11ea-8d5e-914266869517.png">

Without that class
<img width="150" alt="Screen Shot 2020-01-15 at 7 37 19 AM" src="https://user-images.githubusercontent.com/158918/72438211-f7ff0300-3769-11ea-95b0-e360991978aa.png">

**Comment by nickhamze** [comment]
Can we also add this line of CSS to our button?

"outline: 0;" 

I don't like the blue focus states. The core buttons don't have them.

**Comment by Mamaduka** [comment]
@nickhamze I added some fallback colors (https://github.com/sortabrilliant/ps/commit/83b015840b8d0e65461bbbd0dcc7c1535f304068). Can you clear the browser cache and test button colors again?

**Comment by Mamaduka** [comment]
Added `wp-block-button__link` class and removed outline on focus.

**Comment by nickhamze** [comment]
Let's remove the hover state we added:
.wp-block-post-script__button:hover {
	opacity: 0.7;
}

Then I think we are good to launch. Thanks for your help with this.

**Comment by Mamaduka** [comment]
Done.
