### ISSUE TITLE
Button open/close state should be different

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/ps#2]
When someone clicks the button it should change from whatever the text is to a close (X) symbol.

If you go to https://www.intercom.com/ and click on their little icon in the bottom you'll get an idea of what I'm looking for. 

The button size can shrink with a little animation or something.

**Comment by Mamaduka** [comment]
Changed close button text to use &times; (`&times;`) HTML entity.

I also tried adding some basic transition animation, like rotating text but didn't result wasn't good.
