### ISSUE TITLE
Conditionally load theme JavaScript file

### ISSUE THREAD

**Issue by Mamaduka** [sortabrilliant/ps#8]
Currently, the file is always loaded, even if the page doesn't use the block.

**Comment by Mamaduka** [comment]
@nickhamze pushed a fix for this issue.

Did you get a chance to test WP 5.4 compatibility for P.S.?

**Comment by nickhamze** [comment]
@Mamaduka Not yet. I have four left to do that I'll get done later today. They will for sure be done by Monday so you can push the last of the updates.

- PS
- Blockshots
- Whatever
- Altered Reality
